### ISSUE TITLE
login, logout and reset password UI can be improved according to the template

### ISSUE THREAD

**Issue by swasthikcnayak** [swasthikcnayak/sushiksha_placement_prep#10]

**Comment by 18praneeth** [comment]
#12

**Comment by 18praneeth** [comment]
@swasthikcnayak I think we can close this issue now.

**Comment by swasthikcnayak** [comment]
![image](https://user-images.githubusercontent.com/55913708/114995251-40e8be80-9ebb-11eb-8cc5-7306055f39fa.png)
password reset confirm page needs update. The link sent to email opens as above

**Comment by swasthikcnayak** [comment]
also password reset complete page
